const EXTENSION_LANGUAGES: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "javascript",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "typescript",
  css: "css",
  scss: "scss",
  less: "less",
  html: "html",
  htm: "html",
  vue: "html",
  svelte: "html",
  xml: "xml",
  svg: "xml",
  json: "json",
  jsonc: "json",
  md: "markdown",
  markdown: "markdown",
  py: "python",
  rb: "ruby",
  go: "go",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  swift: "swift",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hxx: "cpp",
  cs: "csharp",
  php: "php",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  bat: "bat",
  cmd: "bat",
  yml: "yaml",
  yaml: "yaml",
  toml: "ini",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  lua: "lua",
  dart: "dart",
  r: "r",
  ex: "elixir",
  exs: "elixir",
  clj: "clojure",
  scala: "scala",
};

const getLanguageFromFileName = (fileName: string): string => {
  if (fileName.toLowerCase() === "dockerfile") return "dockerfile";
  const dot = fileName.lastIndexOf(".");
  if (dot <= 0) return "plaintext";
  const ext = fileName.slice(dot + 1).toLowerCase();
  return EXTENSION_LANGUAGES[ext] ?? "plaintext";
};

export { getLanguageFromFileName };
